### ISSUE TITLE
Dead Link in 3rd Paragraph

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/offer-decisioning.en#1]
Issue in ./help/offer-library/create-ranking-strategies.md

At the end of this paragraph...

> For example, you can select a ranking strategy for the email channel and another one for the push channel. For each channel, the trained model system will leverage multiple data points to determine which offer should be presented first for a given placement, rather than taking into account the offers’ priority scores or a [ranking formula](https://experienceleague.adobe.com/docs/offer-decisioning/using/create-components/create-ranking-formulas.html?lang=en).

It should probably be pointing here: https://experienceleague.adobe.com/docs/offer-decisioning/using/create-components/create-ranking-formulas.html%3Flang%3Des

Also, note that the last link returns a 404 if "%3Flang%3Des" is removed.

**Comment by bbringhu** [comment]
The offer-decisioning content has move to experience-platform:

https://experienceleague.adobe.com/docs/journey-optimizer/using/offer-decisioning/rankings/create-ranking-formulas.html
