### ISSUE TITLE
"Segment of visitors"or "Decision rule"

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/offer-decisioning.en#15]
Issue in ./help/offer-library/using/creating-personalized-offers.md

"select the Segment of visitors option"

I think the name of this option has been changed to "Decision rule":
![image](https://user-images.githubusercontent.com/14926804/101229145-c9816380-366c-11eb-9a52-bf1c476e7272.png)

**Comment by lemaitreAdobe** [comment]
screenshot has been updated with Decision rule
