### ISSUE TITLE
"Global Caps" or "Total caps"?

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/offer-decisioning.en#7]
Issue in ./help/get-started/using/glossary.md

The glossary mentions “Global Cap” but the terminology i see in the interface is "Total caps". Does the doc or UI need to be updated?
![image](https://user-images.githubusercontent.com/14926804/101227569-4d841d00-3666-11eb-8302-ad18baff5ff9.png)

**Comment by lemaitreAdobe** [comment]
replaced with "Total caps"
